name: grotesque
version: 0.0.0

category: Web
description: Grotesque is an implementation of GraphQL in Haskell.
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: An implementation of GraphQL.

dependencies:
  - base
  - megaparsec
  - prettyprinter
  - scientific
  - text
ghc-options: -Wall

library:
  source-dirs: library

tests:
  test:
    dependencies:
      - grotesque
      - hedgehog
      - heredoc
      - hspec
      - hspec-megaparsec
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    main: test.hs
    source-dirs: tests
